name: cd
on:
  push:
    branches: [main]


jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Configure AWS Credintials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Configure AWS Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Go 
        run: ./scripts/buildprod.sh

      - name: Build, tag, and push docker image
        run: docker build -t ${{ steps.login-ecr.outputs.registry }}/notely:latest . && docker push ${{ steps.login-ecr.outputs.registry }}/notely:latest
        
