name: ci2

on:
  pull_request:
    branches: [main]

jobs:
  Tests:
    name: Test
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6

      - name: Install go-sec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest 

      - name: Run Tests 
        run: go test ./... 

      - name: Run Security Checks
        run: gosec ./...
  Styles:
    name: Styles
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
      - run: go install honnef.co/go/tools/cmd/staticcheck@2022.1

      - name: Check for Formatting Errors
        run: test -z $(go fmt ./...)

      - name: Check for Linting Errors
        run: staticcheck ./...

