name: ci2

on:
  pull_request:
    branches: [main]

jobs:
  Tests:
    name: Test
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with: 
          go-version: "1.25.1"
      - run: go install github.com/securego/gosec/v2/cmd/gosec@latest 

      - name: Run Tests 
        run: go test ./... 

      - name: Run Security Checks
        run: gosec ./...

  Styles:
    name: Styles
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.1"
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check for Formatting Errors
        run: test -z $(go fmt ./...)

      - name: Check for Linting Errors
        run: staticcheck ./...

